server:
  port: 8282

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hospital_dr?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
    #druid 数据源专有配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 600000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache
    poolPreparedStatements: true
    #配置监控统计拦截的filters，stat:监控统计、log4j：日志记录、wall：防御sql注入
    #filters: stat,wall,log4j,config
    #指定每个连接上PSCache的大小
    maxPoolPreparedStatementPerConnectionSize: 20
    #合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true
    #通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

  # 配置默认的用户名和密码还有用户角色
  security:
    user:
      name: user
      password: 123456
      roles: user


#配置日志地址
logging:
  config: classpath:log/logback_dev.xml

# mybatis
mybatis-plus:
  mapper-locations: classpath:com/hospital_care/hospitalcare/mapper/xml/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.hospital_care.hospitalcare.entity
  #typeEnumsPackage: org.springblade.dashboard.entity.enums
  global-config:
    # 关闭MP3.0自带的banner
    banner: false
    db-config:
      #主键类型  0:"数据库ID自增", 1:"不操作", 2:"用户输入ID",3:"数字型snowflake", 4:"全局唯一ID UUID", 5:"字符串型snowflake";
      id-type: auto
      #字段策略
      insert-strategy: not_null
      update-strategy: not_null
      select-strategy: not_null
      #驼峰下划线转换
      table-underline: true
      # 逻辑删除配置
      # 逻辑删除全局值（1表示已删除，这也是Mybatis Plus的默认配置）
      logic-delete-value: 1
      # 逻辑未删除全局值（0表示未删除，这也是Mybatis Plus的默认配置）
      logic-not-delete-value: 0
      # table-prefix: "t_"
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false


#swagger配置信息
swagger:
  title: hospital_care 接口文档系统
  description: hospital_care 接口文档系统
  version: 1.0.0
  license: Powered By hospital_care
  licenseUrl: http://localhost:8282/swagger-ui/
  terms-of-service-url: http://localhost:8282/swagger-ui/
  contact:
    name: hospital_care
    email: hospital_care@xxx.com
    url: http://localhost:8282/swagger-ui/


jwt:
  secret: hospital_care.com
  expiration: 8640000000



hospitalcare:
  loginUrl: /login
  imgUrl: /login/image
  menuListUrl: /menuList
  icon: /my/icon